openapi: 3.0.0
info:
  title: Cosmo Cats Marketplace API
  version: 1.0.0
  description: API для управления товарами на интергалактическом рынке Космических Котов.

servers:
  - url: http://localhost:8080
    description: Локальный сервер разработки

paths:
  /api/products:
    get:
      summary: Получить список всех продуктов
      description: Возвращает список всех доступных продуктов.
      responses:
        '200':
          description: Список продуктов успешно получен.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Создать новый продукт
      description: Создает новый продукт в системе.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Продукт успешно создан.
        '400':
          description: Ошибка валидации данных.

  /api/products/{id}:
    get:
      summary: Получить продукт по ID
      description: Возвращает продукт по его уникальному идентификатору.
      parameters:
        - name: id
          in: path
          required: true
          description: Уникальный идентификатор продукта.
          schema:
            type: string
      responses:
        '200':
          description: Продукт успешно найден.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Продукт не найден.
    put:
      summary: Обновить продукт по ID
      description: Обновляет информацию о продукте.
      parameters:
        - name: id
          in: path
          required: true
          description: Уникальный идентификатор продукта.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Продукт успешно обновлен.
        '400':
          description: Ошибка валидации данных.
        '404':
          description: Продукт не найден.
    delete:
      summary: Удалить продукт по ID
      description: Удаляет продукт из системы по его идентификатору.
      parameters:
        - name: id
          in: path
          required: true
          description: Уникальный идентификатор продукта.
          schema:
            type: string
      responses:
        '204':
          description: Продукт успешно удален.
        '404':
          description: Продукт не найден.

components:
  schemas:
    Product:
      type: object
      required:
        - name
        - price
      properties:
        id:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          example: "Антигравитационный клубок ниток"
        price:
          type: number
          format: double
          example: 42.5
        description:
          type: string
          example: "Идеальный клубок для межзвездных путешествий."
